-- Generated by scripts/import-catalog.mjs from the static catalogue.
-- Run after schema.sql. Safe to re-run (uses upserts).

insert into products
  (id, sku, name, slug, category, brand, description, price_retail, price_bulk,
   bulk_min_qty, specifications, compatible_vehicles, compatible_gearboxes, tags,
   is_featured, active)
values
  ('c1', 'MNA-CB-0001', 'CVT Steel Push Belt JF011E', 'cvt-steel-push-belt-jf011e', 'cvt_belt', '', 'Genuine-spec steel push belt for Jatco JF011E / RE0F10A CVTs. Hundreds of precision-ground elements riding on two laminated steel rings — the single most load-critical part in a CVT. Replace as a set with worn variator pulleys.', 480, 410, 2, '{"type":"Push belt","elements":"~400","ring":"Dual laminated steel","width":"24mm"}'::jsonb, ARRAY['Nissan X-Trail','Nissan Qashqai','Mitsubishi Outlander','Renault Koleos']::text[], ARRAY['JF011E','RE0F10A']::text[], ARRAY['cvt','belt','push belt','jf011e','variator']::text[], true, true),
  ('c2', 'MNA-CB-0002', 'Variator Pulley Set JF015E', 'variator-pulley-set-jf015e', 'cvt_belt', '', 'Matched primary + secondary variator pulley (cone) set for Jatco JF015E. Mirror-polished sheave faces restore clean ratio sweep and stop belt slip on worn units. Supplied as a balanced pair.', 620, 540, 2, '{"includes":"Primary + secondary cones","finish":"Mirror-polished","condition":"Remanufactured"}'::jsonb, ARRAY['Nissan Almera','Nissan Note','Suzuki Swift']::text[], ARRAY['JF015E','RE0F11A']::text[], ARRAY['cvt','variator','pulley','jf015e']::text[], true, true),
  ('v1', 'MNA-VB-0001', 'CVT Valve Body Reman JF011E', 'cvt-valve-body-reman-jf011e', 'valve_body', '', 'Remanufactured and dyno-tested valve body for JF011E CVTs. Restored bores, new check balls and recalibrated line-pressure circuit — cures harsh engagement, judder and slow ratio response.', 1150, 980, 1, '{"condition":"Remanufactured","tested":"Dyno-tested","solenoids":"Included"}'::jsonb, ARRAY['Nissan X-Trail','Mitsubishi Outlander']::text[], ARRAY['JF011E','RE0F10A']::text[], ARRAY['valve body','cvt','jf011e','reman']::text[], true, true),
  ('v2', 'MNA-VB-0002', 'Line Pressure Solenoid Set', 'line-pressure-solenoid-set', 'valve_body', '', 'Replacement linear solenoid set for CVT and AT valve bodies. Matched resistance and flow for consistent pressure control. Sold as a 3-piece set.', 240, 195, 4, '{"pieces":"3 solenoids","type":"Linear (variable force)","resistance":"5.0Ω ±0.3"}'::jsonb, ARRAY['Nissan','Toyota','Mitsubishi']::text[], ARRAY['JF011E','JF015E','K313']::text[], ARRAY['solenoid','valve body','pressure']::text[], false, true),
  ('t1', 'MNA-TC-0001', 'Torque Converter Reman A750E', 'torque-converter-reman-a750e', 'torque_conv', '', 'Remanufactured torque converter with new lock-up clutch lining and balanced impeller for A750E transmissions. Bench-tested for leak-down and concentricity. Eliminates lock-up shudder and stall-speed drift.', 540, 460, 1, '{"condition":"Remanufactured","lockup":"New lining","tested":"Leak + balance"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner','Lexus GX470']::text[], ARRAY['A750E','A750F']::text[], ARRAY['torque converter','lockup','a750e','reman']::text[], true, true),
  ('1', 'DT-CP-0001', 'AT Clutch Friction Plate 3.5mm', 'at-clutch-friction-plate-3-5mm', 'clutch_plate', '', 'High-performance automatic transmission clutch friction plate. 3.5mm thickness, OEM-equivalent material composition for reliable engagement and long service life.', 28, 22, 10, '{"thickness":"3.5mm","material":"Organic Friction","diameter":"165mm"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner','Isuzu D-Max']::text[], ARRAY['A750E','A750F']::text[], ARRAY['clutch','friction','a750e']::text[], true, true),
  ('2', 'DT-CP-0002', 'HD Clutch Disc A750E', 'hd-clutch-disc-a750e', 'clutch_plate', '', 'Heavy-duty clutch disc designed for A750E transmissions. Enhanced friction material for towing and high-load applications.', 35, 28, 10, '{"thickness":"4.0mm","material":"Kevlar Blend","diameter":"170mm"}'::jsonb, ARRAY['Toyota Land Cruiser','Lexus GX470']::text[], ARRAY['A750E']::text[], ARRAY['clutch','heavy-duty','a750e']::text[], false, true),
  ('3', 'DT-SP-0001', 'Steel Separator Plate 1.8mm', 'steel-separator-plate-1-8mm', 'steel_plate', '', 'Precision-ground steel separator plate for automatic transmissions. Hardened and tempered for consistent performance.', 16, 12, 20, '{"thickness":"1.8mm","material":"Hardened Steel","finish":"Phosphate coated"}'::jsonb, ARRAY['Toyota Hilux','Mitsubishi Triton']::text[], ARRAY['A750E','A340']::text[], ARRAY['steel','separator','plate']::text[], false, true),
  ('4', 'DT-SP-0002', 'Waved Steel Plate A340', 'waved-steel-plate-a340', 'steel_plate', '', 'Waved steel plate for A340 series transmissions. The wave pattern provides controlled clutch engagement.', 20, 15, 20, '{"thickness":"2.0mm","material":"Spring Steel","pattern":"Waved"}'::jsonb, ARRAY['Toyota Hilux','Toyota 4Runner']::text[], ARRAY['A340']::text[], ARRAY['steel','waved','a340']::text[], false, true),
  ('5', 'DT-AF-0001', 'ATF Inline Filter Universal', 'atf-inline-filter-universal', 'auto_filter', '', 'Universal inline ATF filter for automatic transmissions. Catches fine particles and extends transmission fluid life.', 12, 9, 25, '{"type":"Inline","micron":"25μm","connection":"3/8\" barb"}'::jsonb, ARRAY['Universal']::text[], ARRAY['Universal']::text[], ARRAY['filter','inline','universal']::text[], true, true),
  ('6', 'DT-AF-0002', 'Pan Transmission Filter Kit', 'pan-transmission-filter-kit', 'auto_filter', '', 'Complete pan filter kit with gasket. Direct replacement for OEM transmission pan filters.', 25, 19, 15, '{"type":"Pan filter","includes":"Filter + gasket","material":"Felt/Metal mesh"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner']::text[], ARRAY['A750E','A750F']::text[], ARRAY['filter','pan','kit']::text[], false, true),
  ('7', 'DT-FD-0001', 'Forward Clutch Drum A750E', 'forward-clutch-drum-a750e', 'forward_drum', '', 'Complete forward clutch drum assembly for A750E transmissions. Precision machined with new bushing pre-installed.', 120, 95, 3, '{"material":"Cast Aluminum","bushing":"Pre-installed","splines":"36T"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner','Lexus GX470']::text[], ARRAY['A750E']::text[], ARRAY['drum','forward','a750e','assembly']::text[], true, true),
  ('8', 'DT-FD-0002', 'Forward Drum Shell Assembly', 'forward-drum-shell-assembly', 'forward_drum', '', 'Replacement drum shell for various automatic transmissions. Supplied without internal components.', 105, 85, 3, '{"material":"Steel","finish":"Machined","weight":"1.2kg"}'::jsonb, ARRAY['Toyota Hilux','Nissan Navara']::text[], ARRAY['A340','RE5R05A']::text[], ARRAY['drum','shell','assembly']::text[], false, true),
  ('9', 'DT-OP-0001', 'Front Oil Pump Body A340', 'front-oil-pump-body-a340', 'oil_pump', '', 'Remanufactured front oil pump body for A340 transmissions. Restored to OEM specifications with new seals.', 150, 120, 2, '{"type":"Front pump body","condition":"Remanufactured","seals":"Included"}'::jsonb, ARRAY['Toyota Hilux','Toyota 4Runner']::text[], ARRAY['A340']::text[], ARRAY['oil pump','front','a340','reman']::text[], true, true),
  ('10', 'DT-OP-0002', 'Oil Pump Gear Set', 'oil-pump-gear-set', 'oil_pump', '', 'Replacement inner and outer gear set for transmission oil pumps. Hardened steel construction.', 85, 68, 5, '{"type":"Gear set (inner + outer)","material":"Hardened Steel"}'::jsonb, ARRAY['Toyota Hilux','Mitsubishi Triton']::text[], ARRAY['A750E','A340']::text[], ARRAY['oil pump','gears']::text[], false, true),
  ('11', 'DT-PS-0001', 'Bonded Piston Seal Kit A750E', 'bonded-piston-seal-kit-a750e', 'piston_seal', '', 'Complete bonded piston seal kit for A750E automatic transmissions. Includes all required piston seals for a full rebuild.', 14, 10, 20, '{"pieces":"6 seals","material":"Viton rubber bonded to steel","type":"Bonded"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner','Lexus GX470']::text[], ARRAY['A750E']::text[], ARRAY['piston','seal','bonded','a750e']::text[], false, true),
  ('12', 'DT-PS-0002', 'D-Ring Seal Assortment', 'd-ring-seal-assortment', 'piston_seal', '', 'Assorted D-ring seals for automatic transmission hydraulic circuits. Multiple sizes for common applications.', 10, 7.5, 30, '{"pieces":"24 assorted","material":"NBR rubber","sizes":"Mixed (12mm–45mm)"}'::jsonb, ARRAY['Universal']::text[], ARRAY['Universal']::text[], ARRAY['seal','d-ring','assortment']::text[], false, true),
  ('13', 'DT-OK-0001', 'Master Rebuild Kit A750E', 'master-rebuild-kit-a750e', 'overhaul_kit', '', 'Complete master overhaul kit for A750E automatic transmissions. Includes all frictions, steels, seals, gaskets, and bushings needed for a full rebuild.', 250, 195, 2, '{"includes":"Frictions, steels, seals, gaskets, bushings","coverage":"Full overhaul"}'::jsonb, ARRAY['Toyota Hilux','Toyota Fortuner','Lexus GX470']::text[], ARRAY['A750E']::text[], ARRAY['overhaul','rebuild','master','a750e','complete']::text[], true, true),
  ('14', 'DT-OK-0002', 'Banner Kit A340', 'banner-kit-a340', 'overhaul_kit', '', 'Gasket and seal kit (banner kit) for A340 transmissions. Covers all external and internal sealing surfaces.', 160, 128, 3, '{"includes":"Gaskets, O-rings, lip seals, pan gasket","coverage":"Seals only"}'::jsonb, ARRAY['Toyota Hilux','Toyota 4Runner']::text[], ARRAY['A340']::text[], ARRAY['banner','gasket','seal','a340']::text[], false, true),
  ('15', 'DT-LB-0001', 'ATF Dexron VI 1L', 'atf-dexron-vi-1l', 'lubricants', '', 'Premium automatic transmission fluid meeting Dexron VI specifications. Suitable for a wide range of automatic transmissions.', 18, 14, 20, '{"volume":"1 Litre","spec":"Dexron VI","type":"Fully synthetic"}'::jsonb, ARRAY['Universal']::text[], ARRAY['Universal']::text[], ARRAY['atf','dexron','fluid','lubricant']::text[], true, true),
  ('16', 'DT-LB-0002', 'CVT Fluid NS-3 1L', 'cvt-fluid-ns3-1l', 'lubricants', '', 'CVT-specific transmission fluid compatible with Nissan NS-3 specification. For continuously variable transmissions.', 22, 17, 20, '{"volume":"1 Litre","spec":"NS-3 Compatible","type":"Fully synthetic"}'::jsonb, ARRAY['Nissan Navara','Nissan X-Trail','Mitsubishi Outlander']::text[], ARRAY['JF015E','JF011E']::text[], ARRAY['cvt','fluid','ns-3','nissan']::text[], false, true)
on conflict (id) do update set
  sku = excluded.sku, name = excluded.name, slug = excluded.slug,
  category = excluded.category, brand = excluded.brand,
  description = excluded.description, price_retail = excluded.price_retail,
  price_bulk = excluded.price_bulk, bulk_min_qty = excluded.bulk_min_qty,
  specifications = excluded.specifications,
  compatible_vehicles = excluded.compatible_vehicles,
  compatible_gearboxes = excluded.compatible_gearboxes,
  tags = excluded.tags, is_featured = excluded.is_featured, active = excluded.active;

insert into inventory (product_id, stock_qty, reorder_level)
values
  ('c1', 12, 4),
  ('c2', 6, 3),
  ('v1', 4, 2),
  ('v2', 28, 8),
  ('t1', 9, 3),
  ('1', 150, 20),
  ('2', 85, 15),
  ('3', 200, 30),
  ('4', 120, 20),
  ('5', 300, 50),
  ('6', 95, 15),
  ('7', 25, 5),
  ('8', 18, 5),
  ('9', 15, 5),
  ('10', 30, 8),
  ('11', 250, 40),
  ('12', 400, 60),
  ('13', 20, 5),
  ('14', 35, 8),
  ('15', 500, 50),
  ('16', 3, 50)
on conflict (product_id) do update set
  stock_qty = excluded.stock_qty, reorder_level = excluded.reorder_level;
