/* Imports the existing static catalogue from the bengkelgearbox repo and emits:
 *   lib/catalog-seed.json  - used to seed the file-backed store (mockup backend)
 *   supabase/seed.sql      - INSERT statements to seed the live Supabase project
 *
 * The source catalogue is plain JS that assigns window.MNACatalog, so we run it
 * in a sandbox and read the result. Re-run this whenever the static catalogue
 * changes. Usage:
 *   node scripts/import-catalog.mjs [path-to-catalog.js]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import path from 'path'
import vm from 'vm'

const catalogPath =
  process.argv[2] || path.resolve('..', 'bengkelgearbox', 'assets', 'catalog.js')

const code = readFileSync(catalogPath, 'utf8')

// Minimal sandbox: the catalogue only needs `window` at load time.
const sandbox = { window: {}, Intl, encodeURIComponent, Number, console }
vm.createContext(sandbox)
vm.runInContext(code, sandbox)

const cat = sandbox.window.MNACatalog
if (!cat || !Array.isArray(cat.products)) {
  throw new Error('Could not read MNACatalog.products from ' + catalogPath)
}

// Map the storefront product shape to the backend internal shape.
const products = cat.products.map((p) => ({
  id: p.id,
  sku: p.sku,
  name: p.name,
  slug: p.slug,
  category: p.category,
  brand: p.brand || '',
  description: p.description || '',
  priceRetail: p.price,
  priceBulk: p.wholesalePrice,
  bulkMinQty: p.minWholesaleQty,
  specifications: p.specifications || {},
  compatibleVehicles: p.compatibleVehicles || [],
  compatibleGearboxes: p.compatibleGearboxes || [],
  tags: p.tags || [],
  isFeatured: !!p.isFeatured,
  active: true,
}))

const inventory = cat.products.map((p) => ({
  productId: p.id,
  stockQty: p.stockQty ?? 0,
  reorderLevel: p.lowStockThreshold ?? 0,
  updatedAt: '',
}))

mkdirSync(path.resolve('lib'), { recursive: true })
mkdirSync(path.resolve('supabase'), { recursive: true })

writeFileSync(
  path.resolve('lib', 'catalog-seed.json'),
  JSON.stringify({ products, inventory }, null, 2) + '\n',
  'utf8',
)

// ---- Supabase seed SQL ----------------------------------------------------
const q = (v) => `'${String(v).replace(/'/g, "''")}'`
const arr = (a) =>
  a.length ? `ARRAY[${a.map((x) => q(x)).join(',')}]::text[]` : `ARRAY[]::text[]`
const jsonb = (o) => `${q(JSON.stringify(o))}::jsonb`

const productRows = products
  .map(
    (p) =>
      `  (${q(p.id)}, ${q(p.sku)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.category)}, ` +
      `${q(p.brand)}, ${q(p.description)}, ${p.priceRetail}, ${p.priceBulk}, ${p.bulkMinQty}, ` +
      `${jsonb(p.specifications)}, ${arr(p.compatibleVehicles)}, ${arr(p.compatibleGearboxes)}, ` +
      `${arr(p.tags)}, ${p.isFeatured}, ${p.active})`,
  )
  .join(',\n')

const inventoryRows = inventory
  .map((i) => `  (${q(i.productId)}, ${i.stockQty}, ${i.reorderLevel})`)
  .join(',\n')

const sql = `-- Generated by scripts/import-catalog.mjs from the static catalogue.
-- Run after schema.sql. Safe to re-run (uses upserts).

insert into products
  (id, sku, name, slug, category, brand, description, price_retail, price_bulk,
   bulk_min_qty, specifications, compatible_vehicles, compatible_gearboxes, tags,
   is_featured, active)
values
${productRows}
on conflict (id) do update set
  sku = excluded.sku, name = excluded.name, slug = excluded.slug,
  category = excluded.category, brand = excluded.brand,
  description = excluded.description, price_retail = excluded.price_retail,
  price_bulk = excluded.price_bulk, bulk_min_qty = excluded.bulk_min_qty,
  specifications = excluded.specifications,
  compatible_vehicles = excluded.compatible_vehicles,
  compatible_gearboxes = excluded.compatible_gearboxes,
  tags = excluded.tags, is_featured = excluded.is_featured, active = excluded.active;

insert into inventory (product_id, stock_qty, reorder_level)
values
${inventoryRows}
on conflict (product_id) do update set
  stock_qty = excluded.stock_qty, reorder_level = excluded.reorder_level;
`

writeFileSync(path.resolve('supabase', 'seed.sql'), sql, 'utf8')

console.log(`Imported ${products.length} products from ${catalogPath}`)
console.log('Wrote lib/catalog-seed.json and supabase/seed.sql')
